### ISSUE TITLE
Implementation of algorithms being compared

### ISSUE THREAD

**Issue by Eason51** [jamestrimble/ijcai2017-partitioning-common-subgraph#2]
Hi, I am really interested in your proposed MCS algorithm, and I want to try some extensions on it. I wonder if it is possible that I can have a look of the implementations of several algorithms being compared in this project. For example, I seem to not find the following executables or any related source codes.
![image](https://user-images.githubusercontent.com/66631204/218315644-265296e1-fb6f-4f78-940b-3fb0dbd7f6d5.png)
Thank you very much!

**Comment by jamestrimble** [comment]
Hi @Eason51 ,

Sorry it's not better documented. `cp-fc` uses the MCIS solver at https://perso.liris.cnrs.fr/samba-ndojh.ndiaye/recherche_softwares.html . (Actually, I think we used a slightly earlier version, but it should be very similar. It's possible that the command-line options have changed,  though.)

`clique` uses the code from *Clique and Constraint Models for Maximum Common (Connected) Subgraph Problems* available from https://ciaranm.github.io

`kdown` uses the code from *Between Subgraph Isomorphism and Maximum Common Subgraph*, also available at https://ciaranm.github.io

There is a newer, better version of `kdown` that appeared to since our 2017 paper. It's in https://github.com/ciaranm/glasgow-subgraph-solver , isn't it @ciaranm ?

It might also be useful to have a look at my [PhD thesis](https://theses.gla.ac.uk/83350/). One thing to note is that this corrects something that we wrote about McSplit-down in the paper (it's actually better than McSplit on the MCS instances, not worse, overall).

**Comment by Eason51** [comment]
> 

Thank you very much! I will read them through and try them out.

**Comment by Eason51** [comment]
> Hi @Eason51 ,
> 
> Sorry it's not better documented. `cp-fc` uses the MCIS solver at https://perso.liris.cnrs.fr/samba-ndojh.ndiaye/recherche_softwares.html . (Actually, I think we used a slightly earlier version, but it should be very similar. It's possible that the command-line options have changed, though.)
> 
> `clique` uses the code from _Clique and Constraint Models for Maximum Common (Connected) Subgraph Problems_ available from https://ciaranm.github.io
> 
> `kdown` uses the code from _Between Subgraph Isomorphism and Maximum Common Subgraph_, also available at https://ciaranm.github.io
> 
> There is a newer, better version of `kdown` that appeared to since our 2017 paper. It's in https://github.com/ciaranm/glasgow-subgraph-solver , isn't it @ciaranm ?
> 
> It might also be useful to have a look at my [PhD thesis](https://theses.gla.ac.uk/83350/). One thing to note is that this corrects something that we wrote about McSplit-down in the paper (it's actually better than McSplit on the MCS instances, not worse, overall).

Thank you very much! I will read them through and try them out.
